# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
nose=1.3.7=py27_0
openssl=1.0.1k=1
pexpect=3.3=py27_0
pip=7.1.0=py27_1
pyasn1=0.1.7=py27_0
pycrypto=2.6.1=py27_0
python=2.7.10=0
readline=6.2=2
setuptools=18.1=py27_0
sqlite=3.8.4.1=1
system=5.8=2
tk=8.5.18=0
twisted=15.3.0=py27_0
wheel=0.24.0=py27_0
zlib=1.2.8=0
zope.interface=4.1.2=py27_1
